FROM selenium/standalone-firefox

RUN sudo apt update
RUN sudo apt install -y python3 nano && sudo apt install -y python3-pip && pip3 install selenium && pip3 install requests && sudo apt install -y nano && sudo pip3 install requests
RUN sudo pip3 install --upgrade selenium

WORKDIR /app

COPY . /app/

USER root

CMD ["/app/entrypoint.sh"]
